### ISSUE TITLE
Communication issues

### ISSUE THREAD

**Issue by Aiothe** [s0h2x/Immersion-WotLK#1]
Hi, I don't know if you've tested this plugin, but after I use it all interactions with NPCs can't be done anymore, even if I turn off other plugins.

**Comment by s0h2x** [comment]
There is not enough information provided, no screenshots or descriptions. The problem could only be in your client and the addons you have installed.

**Comment by Aiothe** [comment]
Message: Interface\AddOns\Immersion\Logic\Frame.lua:223: ImmersionFrameTalkBoxNameFrameName:SetText(): Font not set
Time: 07/25/23 19:49:45
Count: 2
Stack: [C]: in function `SetText'
Interface\AddOns\Immersion\Logic\Frame.lua:223: in function `UpdateTalkingHead'
Interface\AddOns\Immersion\Logic\Frame.lua:162: in function `HandleGossipOpenEvent'
Interface\AddOns\Immersion\Logic\Events.lua:7: in function `?'
Interface\AddOns\Immersion\Logic\Frame.lua:11: in function <Interface\AddOns\Immersion\Logic\Frame.lua:7>

Locals: (*temporary) = ImmersionFrameTalkBoxNameFrameName {
 0 = <userdata>
 FadeIn = <unnamed> {
 }
}
(*temporary) = "魔导师艾洛娜"
