### ISSUE TITLE
Issue using shaman. NPC wont cast totem.

### ISSUE THREAD

**Issue by ddarville** [s0h2x/Immersion-WotLK#2]
https://www.wowhead.com/wotlk/quest=1521/call-of-earth

Quest Information 

Quest: Call of Earth
QuestId: 1521
Race: Tauren
Map:  1(Kalimdor)
Zone: 215(Mulgore)
Area: 221(Camp Narache)
RequiredItem: 6656(Rough Quartz)

NPC information:
NpcId: 5888

Bug:

After clicking Seer Ravenfeather with required item Rought Quartz npc wont cast totem, disabled the inmersion addon and tried again to talk with Seer Ravenfeather and completed the quest with no issues.

Steps to reproduce the issue:

Create a level 1 Shaman, In area 221(Camp Narache) lookup for Seer Ravenfeather NPC at  X: 44.8 Y: 76.2 and start quest with inmersion addon enabled.

Hope we can fix this issue as soon as possible. Regards. Amazing addon!

**Comment by s0h2x** [comment]
I don't understand what could be the problem with the addon here. Most likely, you simply don't meet the requirements to complete this quest. I have tested it and the problem hasn't been identified.
