### ISSUE TITLE
Add-on bugged. Shaman can't complete Call of Earth chain-quest.

### ISSUE THREAD

**Issue by ddarville** [s0h2x/Immersion-WotLK#3]
Hello, old thread closed without a chance to explain myself better. 

Your add-on is bugged many players low level shaman can't level up using your add-on., please take into consideration the following: 

Fact:
The quest works just fine without your add-on.
If your add-on is Enabled, history quest Call of Earth won't cast totem at the end of the quest. This is a very very important quest for shamans.

All quest requirements are meet. Hope You can understand the issue and please before closing the thread give me a chance to explain. This bug is reported from various players from prívate servers. Hope You can fix this.

**Comment by s0h2x** [comment]
I would gladly fix it if I could at least identify the issue. As I mentioned earlier, all tests were successful, so perhaps the problem lies on the server side where you are playing. It would also be helpful to provide a screenshot or a short video demonstrating the issue for a complete picture.

**Comment by ddarville** [comment]
Hello, i uploaded a video demonstrating the issue:

As you can see with the addon enabled, there is no response from the npc for completing the quest, but after disabling the addon i finished the quest with no problem and totem reward granted.

https://vimeo.com/847640841?share=copy

Hope this helps identifying the issue. The server im testing is running on AzerothCore and these quests are confirmed to work at 100% as show on this video without the addon enabled.

**Comment by Sattva-108** [comment]
Would be nice to have some debug mode for such cases. 
Could be server issue, easily.

**Comment by ddarville** [comment]
How i can enable debug mode? See? this is the problem, you all do not help to identify the issue, just assuming non-sense... Issue is the same on more that 4 servers, you sure you know what you talking about? What makes you believe you all right? Did you take the chance to test yourself the quest? Is just at level 4 for god sake.

If you saw the video correctly, you could see the quest works normal without the addon, when the addon is enabled the quest do not work anymore.

You guys should know that when a quest is bugged on server-side it will not work on any possible way. I demonstrate how the quest work without your addon enabled, so it perfectly means is not on server-side, also please use a warmane client and test is the same thing. 

Whats the meaning of having this project open source if you all do not care of what people say?

Please understand, the issue is everywhere. Many people i know use this addon, they all have the same issue. Please stop assuming things.

**Comment by ddarville** [comment]
It doesnt even make sense to have a invalid tag, when i submitted all proofs of the issue. Last option would be to encourage my friends to also post the issue here to see if that way we can take this seriously man.

**Comment by ddarville** [comment]
> I would gladly fix it if I could at least identify the issue. As I mentioned earlier, all tests were successful, so perhaps the problem lies on the server side where you are playing. It would also be helpful to provide a screenshot or a short video demonstrating the issue for a complete picture.

Could you change my invalid tag please

**Comment by ddarville** [comment]
> I would gladly fix it if I could at least identify the issue. As I mentioned earlier, all tests were successful, so perhaps the problem lies on the server side where you are playing. It would also be helpful to provide a screenshot or a short video demonstrating the issue for a complete picture.

Could you please allow us to help you fix the issue? I provided a video and everything you need.

**Comment by s0h2x** [comment]
> > I would gladly fix it if I could at least identify the issue. As I mentioned earlier, all tests were successful, so perhaps the problem lies on the server side where you are playing. It would also be helpful to provide a screenshot or a short video demonstrating the issue for a complete picture.
> 
> Could you please allow us to help you fix the issue? I provided a video and everything you need.

Well, I watched this video clip, and it's strange that you didn't demonstrate addon behavior by disabling all your additional addons (that's actually the first step in debugging). Difficult to pinpoint the exact cause, but it's definitely not an "error" or a "critical bug" directly related to the quest, based on the video (if I could see it clearly, ofc). It seems like there's an early frame fade happening. As a test, you can quickly click through the dialogue to try and finish it in time. First, try disabling addons and also unchecking fade modes in settings (/immersion).

**Comment by s0h2x** [comment]
fixed: https://github.com/s0h2x/Immersion-WotLK/commit/2de9e2ed82b884e91ce7c14a52140d21bef621b5

**Comment by Arcitec** [comment]
@s0h2x I am just browsing but I want to thank you on behalf of everyone. Finding out that the spell info call broke and devising a workaround is brilliant. :)
