### ISSUE TITLE
Quest Reward panel looks grey out and other issues

### ISSUE THREAD

**Issue by Zergei** [s0h2x/Immersion-WotLK#4]
every time it shows the items as a reward from a quest it shows it one item grey out like this: 
https://i.imgur.com/VOGU9qq.jpg

also i been using a upscaled icon pack from this site [https://github.com/Marotheit/A-Guide-to-Modernizing-the-WotLK-Client](url) and it gives corrupted textures in the quest reward tab. removing the icon pack solved this issue but stii wanted to report an incompability in betweenthat pack and your addon 
https://i.imgur.com/he9dJCm.jpg

and a question where do i get Assasiinss texture mods since there are the only models supported for your addon?
above all that ty so much for backporting this addon to WOTLK

**Comment by s0h2x** [comment]
As for the icons, I am aware of it, but it is unlikely that anything will be fixed regarding that matter. It seems to be a rather suspicious thing that is not properly finished. Additionally, there may be incorrect compression/formatting of texture sizes.

As for the patches from Assasiinss, you can find them through the link in pinned post: https://vk.com/wow_patch

**Comment by s0h2x** [comment]
and btw, I should mention that the color of items has never been changed by their quality. You can simply look at the screenshots from retail version to see that.

**Comment by Zergei** [comment]
> and btw, I should mention that the color of items has never been changed by their quality. You can simply look at the screenshots from retail version to see that.

i have never mentioned the color of item just the part of the reward on the right looks grey out or more darker
![image](https://github.com/s0h2x/Immersion-WotLK/assets/1284407/7a69bf43-92f1-448a-9340-ee849e402585)

instead of your images showcasing the addon does
![image](https://github.com/s0h2x/Immersion-WotLK/assets/1284407/2f9a13ff-eecb-4027-ab48-3ffcd4699938)

**Comment by s0h2x** [comment]
> i have never mentioned the color of item just the part of the reward on the right looks grey out or more darker ![image](https://user-images.githubusercontent.com/1284407/255038749-7a69bf43-92f1-448a-9340-ee849e402585.png)
> 
> instead of your images showcasing the addon does ![image](https://user-images.githubusercontent.com/1284407/255043067-2f9a13ff-eecb-4027-ab48-3ffcd4699938.png)

i'm sorry, but honestly, i don't understand the purpose of this discussion if since you have already compared screenshots and answered your own issue. It's evident that issue lies with addons and "customized" UI compilations that you are using.

Without logs and additional information about addons, i won't be able to fix it.

**Comment by Zergei** [comment]
> > i have never mentioned the color of item just the part of the reward on the right looks grey out or more darker ![image](https://user-images.githubusercontent.com/1284407/255038749-7a69bf43-92f1-448a-9340-ee849e402585.png)
> > instead of your images showcasing the addon does ![image](https://user-images.githubusercontent.com/1284407/255043067-2f9a13ff-eecb-4027-ab48-3ffcd4699938.png)
> 
> i'm sorry, but honestly, i don't understand the purpose of this discussion if since you have already compared screenshots and answered your own issue. It's evident that issue lies with addons and "customized" UI compilations that you are using.
> 
> Without logs and additional information about addons, i won't be able to fix it.

ok ty for the fast reply ill check on my side the addons im using and ill let you know

**Comment by Zergei** [comment]
ok i find it out the responsible of this issue with your addon is ElvUI once i disable it and check again immersion look normal
![WoWScrnShot_072023_221858](https://github.com/s0h2x/Immersion-WotLK/assets/1284407/5f1a79e8-e755-4f78-96cc-2f03e15f6a7e)

**Comment by Zergei** [comment]
well i did some deep check with my addons (before i blame ElvUI) but know is Weak Auras which gives me problems

**Comment by Zergei** [comment]
> 

well looks like the Icon pack i downloaded was corrupted i change it and works like a charm and the other issues are solved as well this addon is really good i love it
